### ISSUE TITLE
Is not binary compatible

### ISSUE THREAD

**Issue by redsteakraw** [uXeBoy/Arduboy_MiSTer#1]
Is not binary compatible it seems to be a RiscV implementation with modified libraries.  I did some digging and there is an FPGA implementation of Atmel chip here https://github.com/jackgassett/AVR8_Shifty it may be worth a look as an alternative to fpgarduino

**Comment by uXeBoy** [comment]
Core is now binary compatible thanks to Iulian Gheorghiu's atmega core! :+1:
